[project]
name = "spark-consumer"
version = "0.1.0"
requires-python = ">=3.11,<3.12"
dependencies = [
  "pyspark==3.5.2",
  "confluent-kafka[protobuf]==2.6.1",
  "protobuf==6.33.2",
]

[tool.uv]
package = false
